#include <linux/version.h>

#define HAVE_ERR_CAST 1
#define HAVE_IPV4_IS_MULTICAST 1
#define HAVE_DEV_DISABLE_LRO 1
#define HAVE_DEV_GET_STATS 1
#if LINUX_VERSION_CODE > KERNEL_VERSION(2,6,32)
#define HAVE_RCU_READ_LOCK_HELD 1
#define HAVE_DEV_GET_BY_INDEX_RCU 1
#endif
#define HAVE_SKB_DST_ACCESSOR_FUNCS 1
#define HAVE_SKB_COPY_FROM_LINEAR_DATA_OFFSET 1
#define HAVE_SKB_RESET_TAIL_POINTER 1
#define HAVE_SKB_COW_HEAD 1
#define HAVE_SKBUFF_HEADER_HELPERS 1
#define HAVE_ICMP6_HDR 1
#define HAVE_SKB_WARN_LRO 1
#define HAVE_CONSUME_SKB 1
#define HAVE_SKB_FRAG_PAGE 1
#define HAVE_SKB_RESET_MAC_LEN 1
#define HAVE_KMEMDUP 1
#define HAVE_BOOL_TYPE 1
#define HAVE_CSUM_TYPES 1
#define HAVE_CSUM_REPLACE4 1
#define HAVE_CSUM_UNFOLD 1
#define HAVE_NLA_NUL_STRING 1
#define HAVE_NLA_GET_BE16 1
#define HAVE_NLA_FIND_NESTED 1
#define HAVE_THIS_CPU_PTR 1
#define HAVE_LOG2_H 1

#ifndef RHEL_RELEASE_VERSION
#define RHEL_RELEASE_VERSION(X, Y)	(0)
#endif
#if LINUX_VERSION_CODE > KERNEL_VERSION(3,10,0) || \
	(defined(RHEL_RELEASE_CODE) && \
	(RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(6, 4)))
#define HAVE_NLA_PUT_BE16 1
#define HAVE_NLA_PUT_BE32 1
#define HAVE_NLA_PUT_BE64 1
#define HAVE___SKB_GSO_SEGMENT 1
#endif

#if LINUX_VERSION_CODE >= KERNEL_VERSION(3,3,0) || \
	(defined(RHEL_RELEASE_CODE) && \
	(RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(6, 4)))
#define HAVE_NETDEV_FEATURES_T
#endif

#if LINUX_VERSION_CODE == KERNEL_VERSION(2,6,32)
#define HAVE_ETH_HW_ADDR_RANDOM 1
#define HAVE_VLAN_SET_ENCAP_PROTO 1
#endif

#if LINUX_VERSION_CODE >= KERNEL_VERSION(3,10,0)
#define HAVE_VLAN_SET_ENCAP_PROTO 1
#endif

#if (defined(RHEL_RELEASE_CODE) && \
	(RHEL_RELEASE_CODE > RHEL_RELEASE_VERSION(6, 4)))
#define HAVE_CAN_CHECKSUM_PROTOCOL
#endif

#if LINUX_VERSION_CODE <= KERNEL_VERSION(3,13,0)
#define HAVE_NET_RANDOM 1
#endif
